package gitlab

import (
	"github.com/flowbaker/flowbaker/pkg/domain"
)

var (
	IntegrationEventType_Push            domain.IntegrationTriggerEventType = "push"
	IntegrationEventType_TagPush         domain.IntegrationTriggerEventType = "tag_push"
	IntegrationEventType_Issue           domain.IntegrationTriggerEventType = "issue"
	IntegrationEventType_Note            domain.IntegrationTriggerEventType = "note"
	IntegrationEventType_MergeRequest    domain.IntegrationTriggerEventType = "merge_request"
	IntegrationEventType_WikiPage        domain.IntegrationTriggerEventType = "wiki_page"
	IntegrationEventType_Pipeline        domain.IntegrationTriggerEventType = "pipeline"
	IntegrationEventType_Job             domain.IntegrationTriggerEventType = "job"
	IntegrationEventType_Deployment      domain.IntegrationTriggerEventType = "deployment"
	IntegrationEventType_Release         domain.IntegrationTriggerEventType = "release"
	IntegrationEventType_GitlabUniversal domain.IntegrationTriggerEventType = "gitlab_universal_trigger"
)

var (
	GitlabSchema = domain.Integration{
		ID:                domain.IntegrationType_Gitlab,
		Name:              "GitLab",
		Description:       "Manage GitLab projects, issues, and releases.",
		CanTestConnection: true,
		CredentialProperties: []domain.NodeProperty{
			{
				Key:         "gitlab_oauth",
				Name:        "GitLab Account",
				Description: "The GitLab account to use for the integration",
				Required:    false,
				Type:        domain.NodePropertyType_OAuth,
				OAuthType:   domain.OAuthTypeGitLab,
			},
		},
		Actions: []domain.IntegrationAction{
			{
				ID:          "create_file",
				Name:        "Create File",
				Description: "Create a new file in a GitLab repository",
				ActionType:  GitlabActionType_CreateFile,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project to create the file in",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "file_path",
						Name:        "File Path",
						Description: "The path to the file in the repository",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:                    "branch",
						Name:                   "Branch",
						Description:            "The branch to create the file in",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Branches,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
						PeekableDependentProperties: []domain.PeekableDependentProperty{
							{PropertyKey: "project_id", ValueKey: "project_id"},
						},
					},
					{
						Key:         "content",
						Name:        "Content",
						Description: "The content of the file",
						Required:    true,
						Type:        domain.NodePropertyType_Text,
					},
					{
						Key:         "commit_message",
						Name:        "Commit Message",
						Description: "The commit message",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "delete_file",
				Name:        "Delete File",
				Description: "Delete a file from a GitLab repository",
				ActionType:  GitlabActionType_DeleteFile,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the file",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "file_path",
						Name:        "File Path",
						Description: "The path to the file to delete",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:                    "branch",
						Name:                   "Branch",
						Description:            "The branch containing the file",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Branches,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
						PeekableDependentProperties: []domain.PeekableDependentProperty{
							{PropertyKey: "project_id", ValueKey: "project_id"},
						},
					},
					{
						Key:         "commit_message",
						Name:        "Commit Message",
						Description: "The commit message for the deletion",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "edit_file",
				Name:        "Edit File",
				Description: "Update an existing file in a GitLab repository",
				ActionType:  GitlabActionType_EditFile,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the file",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "file_path",
						Name:        "File Path",
						Description: "The path to the file to edit",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:                    "branch",
						Name:                   "Branch",
						Description:            "The branch containing the file",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Branches,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
						PeekableDependentProperties: []domain.PeekableDependentProperty{
							{PropertyKey: "project_id", ValueKey: "project_id"},
						},
					},
					{
						Key:         "content",
						Name:        "Content",
						Description: "The new content of the file",
						Required:    true,
						Type:        domain.NodePropertyType_Text,
					},
					{
						Key:         "commit_message",
						Name:        "Commit Message",
						Description: "The commit message for the update",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "get_file",
				Name:        "Get File",
				Description: "Get the content of a file from a GitLab repository",
				ActionType:  GitlabActionType_GetFile,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the file",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "file_path",
						Name:        "File Path",
						Description: "The path to the file",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "ref",
						Name:        "Reference",
						Description: "Branch name, tag, or commit SHA. Defaults to default branch.",
						Required:    false,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "list_files",
				Name:        "List Files",
				Description: "List files in a GitLab repository directory",
				ActionType:  GitlabActionType_ListFiles,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project to list files from",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "path",
						Name:        "Directory Path",
						Description: "The path to the directory. Defaults to root.",
						Required:    false,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "ref",
						Name:        "Reference",
						Description: "Branch name, tag, or commit SHA. Defaults to default branch.",
						Required:    false,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "create_issue",
				Name:        "Create Issue",
				Description: "Create a new issue in a GitLab project",
				ActionType:  GitlabActionType_CreateIssue,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project to create the issue in",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "title",
						Name:        "Title",
						Description: "The title of the issue",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "description",
						Name:        "Description",
						Description: "The description of the issue",
						Required:    false,
						Type:        domain.NodePropertyType_Text,
					},
					{
						Key:         "labels",
						Name:        "Labels",
						Description: "List of labels to apply to the issue",
						Required:    false,
						Type:        domain.NodePropertyType_Array,
						ArrayOpts: &domain.ArrayPropertyOptions{
							ItemType: domain.NodePropertyType_String,
							ItemProperties: []domain.NodeProperty{
								{Key: "label", Name: "Label", Type: domain.NodePropertyType_String},
							},
						},
					},
				},
			},
			{
				ID:          "create_issue_comment",
				Name:        "Create Issue Comment",
				Description: "Create a comment on a GitLab issue",
				ActionType:  GitlabActionType_CreateIssueComment,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the issue",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "issue_iid",
						Name:        "Issue IID",
						Description: "The internal ID of the issue",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "body",
						Name:        "Comment Body",
						Description: "The content of the comment",
						Required:    true,
						Type:        domain.NodePropertyType_Text,
					},
				},
			},
			{
				ID:          "edit_issue",
				Name:        "Edit Issue",
				Description: "Update an existing GitLab issue",
				ActionType:  GitlabActionType_EditIssue,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the issue",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "issue_iid",
						Name:        "Issue IID",
						Description: "The internal ID of the issue",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "title",
						Name:        "Title",
						Description: "New title for the issue",
						Required:    false,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "description",
						Name:        "Description",
						Description: "New description for the issue",
						Required:    false,
						Type:        domain.NodePropertyType_Text,
					},
					{
						Key:         "state",
						Name:        "State",
						Description: "State event to apply",
						Required:    false,
						Type:        domain.NodePropertyType_String,
						Options: []domain.NodePropertyOption{
							{Label: "Close", Value: "close"},
							{Label: "Reopen", Value: "reopen"},
						},
					},
					{
						Key:         "labels",
						Name:        "Labels",
						Description: "List of labels to set on the issue",
						Required:    false,
						Type:        domain.NodePropertyType_Array,
						ArrayOpts: &domain.ArrayPropertyOptions{
							ItemType: domain.NodePropertyType_String,
							ItemProperties: []domain.NodeProperty{
								{Key: "label", Name: "Label", Type: domain.NodePropertyType_String},
							},
						},
					},
				},
			},
			{
				ID:          "get_issue",
				Name:        "Get Issue",
				Description: "Get a specific issue from a GitLab project",
				ActionType:  GitlabActionType_GetIssue,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the issue",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "issue_iid",
						Name:        "Issue IID",
						Description: "The internal ID of the issue",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "lock_issue",
				Name:        "Lock Issue",
				Description: "Lock a GitLab issue to prevent further discussion",
				ActionType:  GitlabActionType_LockIssue,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the issue",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "issue_iid",
						Name:        "Issue IID",
						Description: "The internal ID of the issue to lock",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "create_release",
				Name:        "Create Release",
				Description: "Create a new release in a GitLab project",
				ActionType:  GitlabActionType_CreateRelease,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project to create the release in",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "tag_name",
						Name:        "Tag Name",
						Description: "The tag associated with the release",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "name",
						Name:        "Release Name",
						Description: "The name of the release",
						Required:    false,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "description",
						Name:        "Description",
						Description: "The description of the release (release notes)",
						Required:    false,
						Type:        domain.NodePropertyType_Text,
					},
					{
						Key:         "ref",
						Name:        "Reference",
						Description: "If tag doesn't exist, create from this ref (branch/commit)",
						Required:    false,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "delete_release",
				Name:        "Delete Release",
				Description: "Delete a release from a GitLab project",
				ActionType:  GitlabActionType_DeleteRelease,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the release",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "tag_name",
						Name:        "Tag Name",
						Description: "The tag of the release to delete",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "get_release",
				Name:        "Get Release",
				Description: "Get a specific release from a GitLab project",
				ActionType:  GitlabActionType_GetRelease,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the release",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "tag_name",
						Name:        "Tag Name",
						Description: "The tag of the release to get",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
				},
			},
			{
				ID:          "list_releases",
				Name:        "List Releases",
				Description: "List all releases from a GitLab project",
				ActionType:  GitlabActionType_ListReleases,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project to list releases from",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
				},
			},
			{
				ID:          "update_release",
				Name:        "Update Release",
				Description: "Update an existing release in a GitLab project",
				ActionType:  GitlabActionType_UpdateRelease,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project containing the release",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "tag_name",
						Name:        "Tag Name",
						Description: "The tag of the release to update",
						Required:    true,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "name",
						Name:        "Release Name",
						Description: "New name for the release",
						Required:    false,
						Type:        domain.NodePropertyType_String,
					},
					{
						Key:         "description",
						Name:        "Description",
						Description: "New description for the release",
						Required:    false,
						Type:        domain.NodePropertyType_Text,
					},
				},
			},
			{
				ID:          "get_repository",
				Name:        "Get Repository",
				Description: "Get details of a GitLab project",
				ActionType:  GitlabActionType_GetRepository,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project to get details for",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
				},
			},
			{
				ID:          "get_repository_issues",
				Name:        "Get Repository Issues",
				Description: "Get all issues from a GitLab project",
				ActionType:  GitlabActionType_GetRepositoryIssues,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project to get issues from",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:         "state",
						Name:        "State",
						Description: "Filter by issue state",
						Required:    false,
						Type:        domain.NodePropertyType_String,
						Options: []domain.NodePropertyOption{
							{Label: "All", Value: "all"},
							{Label: "Opened", Value: "opened"},
							{Label: "Closed", Value: "closed"},
						},
					},
				},
			},
			{
				ID:          "user_get_repositories",
				Name:        "Get User Repositories",
				Description: "Get repositories accessible to the authenticated user",
				ActionType:  GitlabActionType_UserGetRepositories,
				Properties: []domain.NodeProperty{
					{
						Key:         "visibility",
						Name:        "Visibility",
						Description: "Filter by repository visibility",
						Required:    false,
						Type:        domain.NodePropertyType_String,
						Options: []domain.NodePropertyOption{
							{Label: "All", Value: ""},
							{Label: "Public", Value: "public"},
							{Label: "Internal", Value: "internal"},
							{Label: "Private", Value: "private"},
						},
					},
					{
						Key:         "order_by",
						Name:        "Order By",
						Description: "Sort order for results",
						Required:    false,
						Type:        domain.NodePropertyType_String,
						Options: []domain.NodePropertyOption{
							{Label: "Created At", Value: "created_at"},
							{Label: "Updated At", Value: "updated_at"},
							{Label: "Name", Value: "name"},
							{Label: "Path", Value: "path"},
						},
					},
				},
			},
		},
		Triggers: []domain.IntegrationTrigger{
			{
				ID:          "gitlab_event_listener",
				Name:        "GitLab Event Listener",
				Description: "Triggers on selected GitLab events for a project",
				EventType:   IntegrationEventType_GitlabUniversal,
				Properties: []domain.NodeProperty{
					{
						Key:                    "project_id",
						Name:                   "Project",
						Description:            "The project to monitor",
						Required:               true,
						Type:                   domain.NodePropertyType_String,
						Peekable:               true,
						PeekableType:           GitlabPeekable_Projects,
						PeekablePaginationType: domain.PeekablePaginationType_Offset,
					},
					{
						Key:              "selected_events",
						Name:             "GitLab Events",
						Description:      "Select one or more GitLab events to trigger this flow",
						Required:         true,
						Type:             domain.NodePropertyType_ListTagInput,
						ExpressionChoice: false,
						Options: []domain.NodePropertyOption{
							{Label: "On Push", Value: string(IntegrationEventType_Push), Description: "Triggered when commits are pushed to a repository"},
							{Label: "On Tag Push", Value: string(IntegrationEventType_TagPush), Description: "Triggered when a tag is pushed to a repository"},
							{Label: "On Issue", Value: string(IntegrationEventType_Issue), Description: "Triggered when an issue is created, updated, or closed"},
							{Label: "On Note", Value: string(IntegrationEventType_Note), Description: "Triggered when a comment is made on an issue, merge request, or commit"},
							{Label: "On Merge Request", Value: string(IntegrationEventType_MergeRequest), Description: "Triggered when a merge request is created, updated, or merged"},
							{Label: "On Wiki Page", Value: string(IntegrationEventType_WikiPage), Description: "Triggered when a wiki page is created or updated"},
							{Label: "On Pipeline", Value: string(IntegrationEventType_Pipeline), Description: "Triggered when a pipeline status changes"},
							{Label: "On Job", Value: string(IntegrationEventType_Job), Description: "Triggered when a job status changes"},
							{Label: "On Deployment", Value: string(IntegrationEventType_Deployment), Description: "Triggered when a deployment occurs"},
							{Label: "On Release", Value: string(IntegrationEventType_Release), Description: "Triggered when a release is created"},
						},
					},
				},
			},
		},
	}
)
